### ISSUE TITLE
Please clarify licence

### ISSUE THREAD

**Issue by yacc143** [ombre42/robotframework-sudslibrary#8]
Your project contains gpl-3.0.txt while setup.py claims Apache License 2.0, which one is relevant?

Thx.

**Comment by ombre42** [comment]
SudsLibrary is licensed using the Apache license.
The GPL is included because small parts of Suds' source code was copied and put in this project. The LGPL requires distribution of the GPL in derivative works if I read it correctly. 
I will rename the file to SUDS_ADJUNCT_LICENSE.txt.
Sorry about the confusion.
